name: Latest blog post workflow
on: 
    workflow_dispatch:  

permissions:
  contents: write
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v7
            - uses: gautamkrishnar/blog-post-workflow@1.9.7
              with: 
                max_post_count: "4"
                feed_list: "https://dev.to/feed/puneet-chandna"
